eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true    
          
server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://10.0.1.6:30006/tep_community?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: combanc
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: tep-community
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        use-new-id-generator-mappings: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  cloud:
    stream:
      bindings:
        output:
          destination: stream1
          content-type: text/plain
        input:
          destination: stream1
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 10.0.1.2
                port: 5672
                username: admin
                password: combanc
                virtual-host: /
  #rabbitMq
#  rabbitmq:
#    host: rabbitmq-headless.rabbitmq
#    port: 5672
#    username: guest
#    password: guest

feign:
  hystrix:
    enabled: true

###配置请求超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 100000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1

swagger:
  enable: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file: admin-client.log
